// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl7MT6JqKB17Ac13uNauqtNYegJce3mFg',
    appId: '1:691196487889:web:65077c626f2b1c91b1bdf0',
    messagingSenderId: '691196487889',
    projectId: 'machinetest-totalx',
    authDomain: 'machinetest-totalx.firebaseapp.com',
    storageBucket: 'machinetest-totalx.appspot.com',
    measurementId: 'G-6RE4045MS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrdeJU51tyRb6XYR0b3Nr6wtp2iw3aAIM',
    appId: '1:691196487889:android:2d620fc5c5a1d2beb1bdf0',
    messagingSenderId: '691196487889',
    projectId: 'machinetest-totalx',
    storageBucket: 'machinetest-totalx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq1WCQjrEN9cYJF-JI9jVS0PdtHzWXIdI',
    appId: '1:691196487889:ios:8930f9af6fbdaf7fb1bdf0',
    messagingSenderId: '691196487889',
    projectId: 'machinetest-totalx',
    storageBucket: 'machinetest-totalx.appspot.com',
    iosBundleId: 'com.example.totalxTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq1WCQjrEN9cYJF-JI9jVS0PdtHzWXIdI',
    appId: '1:691196487889:ios:8930f9af6fbdaf7fb1bdf0',
    messagingSenderId: '691196487889',
    projectId: 'machinetest-totalx',
    storageBucket: 'machinetest-totalx.appspot.com',
    iosBundleId: 'com.example.totalxTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl7MT6JqKB17Ac13uNauqtNYegJce3mFg',
    appId: '1:691196487889:web:ca1540fd5ea491b1b1bdf0',
    messagingSenderId: '691196487889',
    projectId: 'machinetest-totalx',
    authDomain: 'machinetest-totalx.firebaseapp.com',
    storageBucket: 'machinetest-totalx.appspot.com',
    measurementId: 'G-1PG58ERFDQ',
  );
}
